/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Project = {
  _id: string
  _type: "project"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  description?: string
  featured?: boolean
  url?: string
  order?: number
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type Gallery = {
  _id: string
  _type: "gallery"
  _createdAt: string
  _updatedAt: string
  _rev: string
  images?: Array<{
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  }>
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Project
  | Slug
  | Gallery
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./sanity/lib/queries.ts
// Variable: QUERY_FEATURED_PROJECTS
// Query: *[_type == "project" && featured == true] | order(_createdAt asc){    _id,    name,    "slug": slug.current,    description,    featured,    url,    order  }
export type QUERY_FEATURED_PROJECTSResult = Array<{
  _id: string
  name: string | null
  slug: string | null
  description: string | null
  featured: true
  url: string | null
  order: number | null
}>
// Variable: QUERY_ALL_PROJECTS
// Query: *[_type == "project"] | order(order asc){    _id,    name,    "slug": slug.current,    description,    featured,    url,    order  }
export type QUERY_ALL_PROJECTSResult = Array<{
  _id: string
  name: string | null
  slug: string | null
  description: string | null
  featured: boolean | null
  url: string | null
  order: number | null
}>
// Variable: QUERY_GALLERY
// Query: *[_type == "gallery"][0]{    images[]{      _key,      "image": asset->url,      alt,      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height,    }  }
export type QUERY_GALLERYResult = {
  images: Array<{
    _key: string
    image: string | null
    alt: string | null
    width: number | null
    height: number | null
  }> | null
} | null

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project" && featured == true] | order(_createdAt asc){\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    featured,\n    url,\n    order\n  }\n': QUERY_FEATURED_PROJECTSResult
    '\n  *[_type == "project"] | order(order asc){\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    featured,\n    url,\n    order\n  }\n': QUERY_ALL_PROJECTSResult
    '\n *[_type == "gallery"][0]{\n    images[]{\n      _key,\n      "image": asset->url,\n      alt,\n      "width": asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height,\n    }\n  }\n': QUERY_GALLERYResult
  }
}
