import { defineField, defineType } from "sanity";
import { navLinksData } from "@/constants/navigation";
import { formatDate } from "@/lib/utils";

export const projectTags = [
  "Open Source",
  "Web3",
  "Blockchain",
  "Crypto",
  "DeFi",
  "NFT",
  "DAO",
  "Smart Contracts",
  "Ethereum",
  "Solana",
  "Base",
  "AI",
  "Machine Learning",
  "LLM",
  "Generative AI",
  "Developer",
  "Developer Tools",
  "CLI",
  "SDK",
  "API",
  "SaaS",
  "B2B",
  "Productivity",
  "Automation",
  "Analytics",
  "Dashboard",
  "E-commerce",
  "Fintech",
  "Social",
  "Community",
  "Education",
  "Portfolio",
  "Blog",
  "CMS",
  "Design System",
  "UI",
  "UX",
  "Components",
  "Frontend",
  "Backend",
  "Full Stack",
  "React",
  "Next.js",
  "TypeScript",
  "JavaScript",
  "Node.js",
  "Bun",
  "Rust",
  "Go",
  "Python",
  "Database",
  "PostgreSQL",
  "Supabase",
  "Firebase",
  "Authentication",
  "Payments",
  "Security",
  "DevOps",
  "Cloud",
  "Infrastructure",
  "Testing",
  "Monitoring",
  "Developer Experience",
  "API Tooling",
  "Browser Extension",
  "Mobile",
  "Desktop",
  "Experimental",
  "Creative Coding",
  "Automation",
  "Personal",
] as const;

export const projectSchema = defineType({
  name: "project",
  title: "Projects",
  type: "document",
  icon: navLinksData("/projects")?.icon,
  fields: [
    defineField({
      name: "name",
      type: "string",
      title: "Project Name",
    }),
    defineField({
      name: "url",
      type: "url",
      title: "Project Url",
    }),
    defineField({
      name: "mainImage",
      type: "image",
      title: "Main Image",
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: "date",
      type: "datetime",
      title: "When was this project built?",
    }),
    defineField({
      name: "description",
      type: "text",
      title: "A brief about this project",
    }),
    defineField({
      name: "tags",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: projectTags.map((tag) => ({
          title: tag,
          value: tag,
        })),
      },
    }),
    defineField({
      name: "filters",
      title: "Project Filters",
      type: "array",
      of: [{ type: "reference", to: [{ type: "projectFilter" }] }],
      options: { layout: "tags" },
      validation: (Rule) => Rule.max(3).error("You can add up to 3 filters"),
    }),
  ],
  preview: {
    select: {
      title: "name",
      media: "mainImage",
      date: "date",
    },
    prepare({ title, media, date }) {
      return {
        title,
        subtitle: date ? formatDate(date) : undefined,
        media,
      };
    },
  },
});
